// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Area struct {
	AreaID  int64
	ParamID pgtype.Text
	Name    pgtype.Text
	Country pgtype.Text
}

type Crag struct {
	CragID            int64
	AreaID            pgtype.Int8
	ParamID           pgtype.Text
	PremiumTopoActive pgtype.Bool
	Latitude          pgtype.Float8
	Longitude         pgtype.Float8
	Name              pgtype.Text
	Info              pgtype.Text
	Url               pgtype.Text
}

type Route struct {
	RouteID   int64
	SectorID  pgtype.Int8
	CragID    pgtype.Int8
	Title     pgtype.Text
	Grade     pgtype.Text
	RouteType pgtype.Text
}

type Sector struct {
	SectorID  int64
	CragID    pgtype.Int8
	Name      pgtype.Text
	Url       pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
}
