// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFavoriteClimbList = `-- name: CreateFavoriteClimbList :one
INSERT INTO user_favourite_lists (name, description, owner)
VALUES ($1, $2, $3)
RETURNING id, name, description, owner
`

type CreateFavoriteClimbListParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Owner       string      `json:"owner"`
}

func (q *Queries) CreateFavoriteClimbList(ctx context.Context, arg CreateFavoriteClimbListParams) (UserFavouriteList, error) {
	row := q.db.QueryRow(ctx, createFavoriteClimbList, arg.Name, arg.Description, arg.Owner)
	var i UserFavouriteList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Owner,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email) VALUES ($1)
RETURNING id, email, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFavoriteClimbsList = `-- name: GetFavoriteClimbsList :many
SELECT id, name, description, owner from user_favourite_lists
WHERE owner = $1
`

func (q *Queries) GetFavoriteClimbsList(ctx context.Context, owner string) ([]UserFavouriteList, error) {
	rows, err := q.db.Query(ctx, getFavoriteClimbsList, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFavouriteList
	for rows.Next() {
		var i UserFavouriteList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRouteById = `-- name: GetRouteById :one
SELECT 
  r.route_id,
  r.title,
  r.grade,
  r.route_type,
  r.description,
  r.images ->> 'main' as image_main,
  r.images ->> 'thumbnail' as image_thumbnail
FROM  route as r
WHERE r.route_id = $1
LIMIT 1
`

type GetRouteByIdRow struct {
	RouteID        int64       `json:"route_id"`
	Title          pgtype.Text `json:"title"`
	Grade          pgtype.Text `json:"grade"`
	RouteType      pgtype.Text `json:"route_type"`
	Description    pgtype.Text `json:"description"`
	ImageMain      interface{} `json:"image_main"`
	ImageThumbnail interface{} `json:"image_thumbnail"`
}

func (q *Queries) GetRouteById(ctx context.Context, routeID int64) (GetRouteByIdRow, error) {
	row := q.db.QueryRow(ctx, getRouteById, routeID)
	var i GetRouteByIdRow
	err := row.Scan(
		&i.RouteID,
		&i.Title,
		&i.Grade,
		&i.RouteType,
		&i.Description,
		&i.ImageMain,
		&i.ImageThumbnail,
	)
	return i, err
}

const getRoutes = `-- name: GetRoutes :many
SELECT route_id, sector_id, crag_id, title, grade, route_type, images, description FROM route
ORDER BY title
LIMIT 100
`

func (q *Queries) GetRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, getRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.RouteID,
			&i.SectorID,
			&i.CragID,
			&i.Title,
			&i.Grade,
			&i.RouteType,
			&i.Images,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutesByName = `-- name: GetRoutesByName :many
SELECT 
  r.route_id,
  r.title,
  r.grade,
  c.name as grag_name,
  s.name as sector_name,
  s.sector_id as sector_id
FROM route as r
JOIN 
  sector as s 
ON 
  s.sector_id = r.sector_id
JOIN
  crag as c 
ON
  c.crag_id = r.crag_id
JOIN areas AS a 
ON 
  c.area_id = a.area_id 
WHERE
  r.title ILIKE $1
AND 
  a.country = 'Finland'
ORDER
  by r.title
LIMIT 15
`

type GetRoutesByNameRow struct {
	RouteID    int64       `json:"route_id"`
	Title      pgtype.Text `json:"title"`
	Grade      pgtype.Text `json:"grade"`
	GragName   pgtype.Text `json:"grag_name"`
	SectorName pgtype.Text `json:"sector_name"`
	SectorID   int64       `json:"sector_id"`
}

func (q *Queries) GetRoutesByName(ctx context.Context, title pgtype.Text) ([]GetRoutesByNameRow, error) {
	rows, err := q.db.Query(ctx, getRoutesByName, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoutesByNameRow
	for rows.Next() {
		var i GetRoutesByNameRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Title,
			&i.Grade,
			&i.GragName,
			&i.SectorName,
			&i.SectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutesBySector = `-- name: GetRoutesBySector :many
SELECT 
  r.route_id,
  r.title,
  r.route_type,
  r.grade,
  r.images ->> 'main' as image_main,
  r.images ->> 'thumbnail' as image_thumbnail,
  s.name as sector_name
FROM route as r
JOIN sector as s
  ON s.sector_id = r.sector_id
WHERE
  r.sector_id = $1
`

type GetRoutesBySectorRow struct {
	RouteID        int64       `json:"route_id"`
	Title          pgtype.Text `json:"title"`
	RouteType      pgtype.Text `json:"route_type"`
	Grade          pgtype.Text `json:"grade"`
	ImageMain      interface{} `json:"image_main"`
	ImageThumbnail interface{} `json:"image_thumbnail"`
	SectorName     pgtype.Text `json:"sector_name"`
}

func (q *Queries) GetRoutesBySector(ctx context.Context, sectorID pgtype.Int8) ([]GetRoutesBySectorRow, error) {
	rows, err := q.db.Query(ctx, getRoutesBySector, sectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoutesBySectorRow
	for rows.Next() {
		var i GetRoutesBySectorRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Title,
			&i.RouteType,
			&i.Grade,
			&i.ImageMain,
			&i.ImageThumbnail,
			&i.SectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectors = `-- name: GetSectors :many
SELECT 
  s.latitude,
  s.longitude,
  s.name,
  s.sector_id,
  c.name as crag_name,
  c.crag_id as crag_id
FROM sector AS s 
INNER JOIN crag AS c 
  on s.crag_id = c.crag_id 
JOIN areas AS a 
  on c.area_id = a.area_id 
WHERE a.country = 'Finland'
`

type GetSectorsRow struct {
	Latitude  pgtype.Float8 `json:"latitude"`
	Longitude pgtype.Float8 `json:"longitude"`
	Name      pgtype.Text   `json:"name"`
	SectorID  int64         `json:"sector_id"`
	CragName  pgtype.Text   `json:"crag_name"`
	CragID    int64         `json:"crag_id"`
}

func (q *Queries) GetSectors(ctx context.Context) ([]GetSectorsRow, error) {
	rows, err := q.db.Query(ctx, getSectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSectorsRow
	for rows.Next() {
		var i GetSectorsRow
		if err := rows.Scan(
			&i.Latitude,
			&i.Longitude,
			&i.Name,
			&i.SectorID,
			&i.CragName,
			&i.CragID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, updated_at FROM users WHERE email = $1 
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFavuriteClimbsItems = `-- name: InsertFavuriteClimbsItems :many
INSERT INTO user_favourite_climb_items (route_id, favourite_climb_list)
SELECT unnest($1::int[]), $2::uuid
RETURNING id, route_id, favourite_climb_list
`

type InsertFavuriteClimbsItemsParams struct {
	Column1 []int32     `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) InsertFavuriteClimbsItems(ctx context.Context, arg InsertFavuriteClimbsItemsParams) ([]UserFavouriteClimbItem, error) {
	rows, err := q.db.Query(ctx, insertFavuriteClimbsItems, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFavouriteClimbItem
	for rows.Next() {
		var i UserFavouriteClimbItem
		if err := rows.Scan(&i.ID, &i.RouteID, &i.FavouriteClimbList); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRouteById = `-- name: UpdateRouteById :one
UPDATE route
SET 
  title       = CASE WHEN $1::text   IS NOT NULL THEN $1::text   ELSE title END,
  grade       = CASE WHEN $2::text   IS NOT NULL THEN $2::text   ELSE grade END,
  route_type  = CASE WHEN $3::text   IS NOT NULL THEN $3::text   ELSE route_type END,
  images      = CASE WHEN $4::jsonb  IS NOT NULL THEN $4::jsonb  ELSE images END,
  description = CASE WHEN $5::text   IS NOT NULL THEN $5::text   ELSE description END
WHERE route_id = $6
RETURNING route_id, sector_id, crag_id, title, grade, route_type, images, description, images ->> 'main' AS image_main, images ->> 'thumbnail' AS image_thumbnail
`

type UpdateRouteByIdParams struct {
	Title       string `json:"title"`
	Grade       string `json:"grade"`
	RouteType   string `json:"route_type"`
	Images      []byte `json:"images"`
	Description string `json:"description"`
	RouteID     int64  `json:"route_id"`
}

type UpdateRouteByIdRow struct {
	RouteID        int64       `json:"route_id"`
	SectorID       pgtype.Int8 `json:"sector_id"`
	CragID         pgtype.Int8 `json:"crag_id"`
	Title          pgtype.Text `json:"title"`
	Grade          pgtype.Text `json:"grade"`
	RouteType      pgtype.Text `json:"route_type"`
	Images         []byte      `json:"images"`
	Description    pgtype.Text `json:"description"`
	ImageMain      interface{} `json:"image_main"`
	ImageThumbnail interface{} `json:"image_thumbnail"`
}

func (q *Queries) UpdateRouteById(ctx context.Context, arg UpdateRouteByIdParams) (UpdateRouteByIdRow, error) {
	row := q.db.QueryRow(ctx, updateRouteById,
		arg.Title,
		arg.Grade,
		arg.RouteType,
		arg.Images,
		arg.Description,
		arg.RouteID,
	)
	var i UpdateRouteByIdRow
	err := row.Scan(
		&i.RouteID,
		&i.SectorID,
		&i.CragID,
		&i.Title,
		&i.Grade,
		&i.RouteType,
		&i.Images,
		&i.Description,
		&i.ImageMain,
		&i.ImageThumbnail,
	)
	return i, err
}
