// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoutes = `-- name: GetRoutes :many
SELECT route_id, sector_id, crag_id, title, grade, route_type FROM route
ORDER BY title
LIMIT 100
`

func (q *Queries) GetRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, getRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.RouteID,
			&i.SectorID,
			&i.CragID,
			&i.Title,
			&i.Grade,
			&i.RouteType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutesByName = `-- name: GetRoutesByName :many
SELECT 
  r.title,
  r.grade,
  c.name as grag_name,
  s.name as sector_name
FROM route as r
JOIN 
  sector as s 
ON 
  s.sector_id = r.sector_id
JOIN
  crag as c 
ON
  c.crag_id = r.crag_id
WHERE
  r.title ILIKE $1
ORDER
  by r.title
LIMIT 50
`

type GetRoutesByNameRow struct {
	Title      pgtype.Text
	Grade      pgtype.Text
	GragName   pgtype.Text
	SectorName pgtype.Text
}

func (q *Queries) GetRoutesByName(ctx context.Context, title pgtype.Text) ([]GetRoutesByNameRow, error) {
	rows, err := q.db.Query(ctx, getRoutesByName, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoutesByNameRow
	for rows.Next() {
		var i GetRoutesByNameRow
		if err := rows.Scan(
			&i.Title,
			&i.Grade,
			&i.GragName,
			&i.SectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
